# Toeiie - 6 Jun
happy_birth_day_toeiie:
  class: HappyBirthDayWorker
  args: ['อะไรจะเกิดก็ปล่อยให้มันเกิด แต่วันที่โทอี้เกิดเราจะไม่ปล่อยไปเสยๆ แฮปปี้เบิร์ดเดย์ เย่ๆๆๆ 🧁🥳', { stickerPackageId: 1070, stickerId: 17843 }]
  cron: '0 0 6 6 * Asia/Bangkok'

# Yong - 16 Sep
happy_birth_day_yong:
  class: HappyBirthDayWorker
  args: ['วันนี้งอลอะไรอีกมั๊ยยย หายงอลได้แล้วนะย้งมาแฮปปี้เบิร์ดเดย์แล้วววว วู้ววๆๆๆ 🥮🎊', { stickerPackageId: 1070, stickerId: 17878 }]
  cron: '0 0 16 9 * Asia/Bangkok'

# Maggy - 20 Oct
happy_birth_day_maggy:
  class: HappyBirthDayWorker
  args: ['แม็กกี้วันนี้ได้นอนหรือยัง ถ้ายังก็นอนได้แล้ววว ก่อนนอนเป่าเค้กด้วยยย แฮปปี้เบิร์ดเดย์ คร่อกๆๆๆๆ 🎂🎉', { stickerPackageId: 1070, stickerId: 17841 }]
  cron: '0 0 20 10 * Asia/Bangkok'

#        * * * * *
#        - - - - -
#        | | | | |
#        | | | | ----- Day of week (0 - 7) (Sunday=0 or 7)
#        | | | ------- Month (1 - 12)
#        | | --------- Day of month (1 - 31)
#        | ----------- Hour (0 - 23)
#        ------------- Minute (0 - 59)
